# /opt/ros/galactic/share/nav2_bringup/params/nav2_params.yaml

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: True
    planner_plugins: ["trajectory_planner"]
    trajectory_planner:
      plugin: "trajectory_planner/TrajectoryPlanner"
      # The number of steps the whole circle (2 * pi) is divided by to create
      # the three-dimensional cost maps.
      angle_granularity: 360
      # The distance up to which obstacles are inflated to calculate the costs.
      inflation_radius: 5.0
      # The directory to store costs to for a faster start-up of the planner with
      # the same map. Disable caching of costs by setting this to "".
      cache_directory: "/tmp"
      # The directory to write debug images to when creating the cost maps. Disable
      # this by setting this to "".
      debug_directory: "/tmp"

global_costmap:
  global_costmap:
    ros__parameters:
      footprint_padding: 0.05
      footprint: "[[-0.2, 0.2], [0.3, 0.2], [0.45, 0.05], [0.45, -0.05], [0.3, -0.2], [-0.2, -0.2]]"
